### ISSUE TITLE
Feature request: let the user define the key to start keytty with. 

### ISSUE THREAD

**Issue by endrebak** [keytty/shelter#3]
I have a heavily modified keyboard layout with karabiner-elements. That means I cannot use keytty because the 
command key is already heavily overloaded. I guess this will be the case for many people interested in this app.

Therefore it would be neat if one could select the button to use to start keytty oneself. The fact that it uses Command prevents me from using this app :/ Now the keytty command line pops up every other second.

**Comment by endrebak** [comment]
@ryuheechul Sorry for pinging, but you aren't watching the repo :)

**Comment by ryuheechul** [comment]
Hi @endrebak, this repo is used only for maintaing releases not meant for issue tracking of new features. However, I will still answer your questions :). At this point, the current version of Keytty supports mostly only to deal with the new macOS version whenever I can. I define the current version as not very maintainable and I'm planning to rewrite an open-source version and I will take into account your suggestion when I get to work on it. In fact, that's one of my goals with the new version.

Right now I'm working on a full-time job and find it difficult to find a time to work on it intensively though. So currently it's very slow 😢. Thanks for using it anyway!
